# Generated by Django 5.0.7 on 2024-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_car_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
